### PR TITLE
feat(to-react-native): allow ability to format keys

### PR DESCRIPTION
**Pull request by ridafkih**
Adds the option `formatKeys` on the `to-react-native` parser, allowing you to select between kebab, camel, snake, and pascal casing, defaulting to camel casing.

### CODE REVIEW

**Comment by ridafkih** [comment]
@AMoreaux If I could get someone to have a look-see, that'd be great. Our team is trying to leverage this feature as soon as possible.

**Comment by AMoreaux** [comment]
I'm reviewing the PR 😉

**Review by AMoreaux — APPROVED** [review]

**Comment by AMoreaux** [comment]
Thx for the contribution @ridafkih , I will tell you when it will be available In production.

**Comment by AMoreaux** [comment]
It's deployed 👌
I will reply tomorrow to your issue https://github.com/Specifyapp/parsers/issues/164
If you have any other feedback, don't hesitate to tell us, it's priceless for us 😉

**Pull request merged**
